Add Group CRUD capabilities
UnityFoundation-io/Libre311 pull request #106
Opened 2024-02-20 22:48 UTC by montesmoci

2024-02-21 17:38 UTC, HootDunk requested changes

2024-02-21 17:38 UTC, HootDunk commented on app/src/main/java/app/service/service/ServiceService.java
> +            return null;
Can throw exception here

2024-02-21 22:45 UTC, montesmoci commented on app/src/main/java/app/service/service/ServiceService.java
> +                return null;
Agreed. I've brought this up in the past and it is planned item for refactor. See [Tech Debt: Error Handling On Front & Backend](https://3.basecamp.com/5573843/buckets/31824829/card_tables/cards/6918499708/edit?focus=kanban_card_title)

2024-02-21 22:53 UTC, montesmoci commented on app/src/main/java/app/JurisdictionAdminController.java
> +                .headers(Map.of(
Sounds good, I'll make the update. I was following a similar pattern that we've used for list endpoint in root controller See `getServiceRequestsJson` and `indexJson`

2024-02-22 03:00 UTC, montesmoci commented on app/src/main/java/app/JurisdictionAdminController.java
> +    public HttpResponse<List<GroupDTO>> indexGroups(@Valid Pageable pageable, @Nullable @QueryValue("jurisdiction_id") String jurisdiction_id) {
Removing `@Nullable` produces the following error:

```
error: The uri variable [jurisdiction_id] is optional, but the corresponding method argument [java.lang.String jurisdiction_id] is not defined as an Optional or annotated with a Nullable annotation.
    public Page<GroupDTO> indexGroups(@Valid Pageable pageable, @QueryValue("jurisdiction_id") String jurisdiction_id) {

```

2024-02-22 18:06 UTC, HootDunk commented on app/src/main/java/app/JurisdictionAdminController.java
> +    public HttpResponse<List<GroupDTO>> indexGroups(@Valid Pageable pageable, @Nullable @QueryValue("jurisdiction_id") String jurisdiction_id) {
Thanks for checking and including the error

2024-02-26 17:42 UTC, HootDunk approved these changes

2024-02-26 17:50 UTC, merged