Frontend/add service
UnityFoundation-io/Libre311 pull request #122
Opened 2024-02-28 20:24 UTC by JackDiSalvatore

Steps to test:

1. Log in as an admin (ex: unity_admin@example.com)
2. Through the Menu Drawer, navigate to the Service Definition Editor (do not use the url directly)
3. Click any Group from the list
4. Click the "+ Add Service" Icon at the top right
5. Enter in any information you wish, but you must make sure the "Definition" is a valid Service Definition JSON.  I will paste an example below for you to use

Valid Defintion JSON:
```
{
    "service_code": "202",
    "attributes": [
        {
            "variable": true,
            "code": "BUS_STOP",
            "datatype": "multivaluelist",
            "required": true,
            "datatype_description": "Please select one or more items.",
            "order": 1,
            "description": "Please select one or more items that best describe the issue. If Other, please elaborate in the Description field below.",
            "values": [
                {
                    "key": "UNSAFE",
                    "name": "Unsafe location"
                },
                {
                    "key": "NO_SDWLK",
                    "name": "No sidewalk"
                },
                {
                    "key": "MISSING_SIGN",
                    "name": "Sign missing"
                },
                {
                    "key": "NO_SHELTER",
                    "name": "No Shelter"
                },
                {
                    "key": "OTHER",
                    "name": "Other"
                }
            ]
        }
    ]
}
```

<img width="701" alt="Screenshot 2024-02-28 at 2 16 47 PM" src="https://github.com/UnityFoundation-io/Libre311/assets/17691434/47512c91-1f63-4e65-a1c3-39b31b4d421a">

2024-02-28 20:26 UTC, JackDiSalvatore commented on frontend/src/lib/services/Libre311/Libre311.ts
> +// ************************************************ //
Hopefully our naming conventions do not get confusing but my understanding is as follows

Create Service Request - means the "Request" used to create a new "Service"
Create Service Request Request - would mean the "Request" used to create a new "Service Request"

2024-02-28 21:19 UTC, zsbrown97 submitted a review, later dismissed

2024-02-28 22:28 UTC, HootDunk commented on frontend/src/lib/services/Libre311/Libre311.ts
> +	async createService(params: CreateServiceRequest): Promise<CreateServiceResponse> {
Is the formatting turned on here?

2024-02-28 22:28 UTC, HootDunk commented on frontend/src/lib/services/Libre311/Libre311.ts
> +				data = res.data[0 as keyof typeof unknown];
I don't think this if block is needed.  The parse method should properly narrow the type.

2024-02-28 22:32 UTC, HootDunk commented on frontend/src/routes/groups/[group_id]/+page.svelte
> +				service_code: newServiceCode.value ?? '',
Service codes have to be unique across jurisdictions so if we default to an empty string it will work once and then start erroring out.

2024-02-28 22:35 UTC, HootDunk commented on frontend/src/routes/groups/[group_id]/+page.svelte
> +				group_id: newServiceGroupId.value ?? -1
Are all of the nullish coalesces needed?  If they are showing up as `optional` it could be a problem of not doing the type narrowing correctly.

2024-02-28 22:39 UTC, HootDunk commented on frontend/src/lib/services/Libre311/Libre311.ts
> +export type CreateServiceRequest = z.infer<typeof CreateServiceRequestSchema>;
Imo the naming should be `CreateServiceParams`
We have the `createService` method and it expects params of type `CreateServiceParams`
That at least mirrors the `createServiceRequest` method which expects params of type `CreateServiceRequestParams`

2024-02-29 16:37 UTC, JackDiSalvatore commented on frontend/src/lib/services/Libre311/Libre311.ts
> +	async createService(params: CreateServiceRequest): Promise<CreateServiceResponse> {
I believe so

2024-02-29 17:10 UTC, HootDunk requested changes
I think the group id shouldn't be something that the user enters.  I think when they select a service, it will be within a group so we will no the group in that moment.

2024-02-29 17:19 UTC, montesmoci approved these changes

2024-02-29 17:19 UTC, montesmoci commented on app/src/main/java/app/JurisdictionAdminController.java
Sounds good! I'll create a follow up PR that changes Admin endpoints to return a single object where appropriate.

2024-02-29 17:34 UTC, JackDiSalvatore commented
> I think the group id shouldn't be something that the user enters. I think when they select a service, it will be within a group so we will no the group in that moment.

So we really "have" to get the groups before we do the services -_-

2024-02-29 17:54 UTC, HootDunk commented
> > I think the group id shouldn't be something that the user enters. I think when they select a service, it will be within a group so we will no the group in that moment.
> 
> So we really "have" to get the groups before we do the services -_-

Yeah I suppose so, fortunately the endpoint to load groups exists on the backend so we just need to create the Libre311 interface method to load it.

2024-02-29 19:54 UTC, HootDunk approved these changes

2024-02-29 19:55 UTC, merged