New Map Component
UnityFoundation-io/Libre311 pull request #41
Opened 2024-01-22 18:28 UTC by zsbrown97

Made components for Map (using Leaflet) and map markers (circles and waypoints).

2024-01-22 18:51 UTC, HootDunk requested changes
Looks good!  I made a couple of comments for changes but overall it's coming together :+1:

2024-01-22 18:51 UTC, HootDunk commented on frontend/src/lib/components/MapComponent.svelte
> +<script lang="ts">
This file needs to be formatted with prettier (I recommend the format on save setting so that you don't have to remember to manually format)

2024-01-22 18:51 UTC, HootDunk commented on package.json
> +  "dependencies": {
These dependencies should be added to the package.json inside of "libre311/frontend" instead of the root

2024-01-22 18:51 UTC, HootDunk commented on frontend/src/lib/components/MapComponent.svelte
> +			.on('popupopen', async (e) => {
You can remove the 'zoom' and 'popupopen' listeners for now.  We can add them back in if the need arises.

2024-01-22 18:51 UTC, HootDunk commented on frontend/src/lib/components/MapComponent.svelte
> +	const dispatch = createEventDispatcher();
Once the zoom listener is removed you can take this out

2024-01-22 19:10 UTC, JackDiSalvatore submitted a review, later dismissed

2024-01-23 15:52 UTC, JackDiSalvatore approved these changes

2024-01-23 16:03 UTC, HootDunk submitted a review, later dismissed

2024-01-23 16:20 UTC, JackDiSalvatore approved these changes

2024-01-23 16:20 UTC, HootDunk approved these changes

2024-01-23 16:24 UTC, merged