Phone number validation
UnityFoundation-io/Libre311 pull request #66
Opened 2024-02-01 20:19 UTC by zsbrown97

Phone number validation better than ever. Zero duct tape used in the final product

2024-02-01 21:14 UTC, HootDunk commented on package.json
>  {
This package json can be deleted

2024-02-01 21:15 UTC, HootDunk commented on package.json
> +    "google-libphonenumber": "^3.2.34"
move this to dependencies in `frontend/package.json`

2024-02-01 21:15 UTC, HootDunk commented on package.json
> +    "@types/google-libphonenumber": "^7.4.30",
move this to devDependencies in `frontend/package.json`

2024-02-01 21:16 UTC, HootDunk commented on package.json
> +    "@types/node": "^20.11.16"
Do we need this dependency?

2024-02-02 20:19 UTC, JackDiSalvatore requested changes

2024-02-02 20:19 UTC, JackDiSalvatore commented on frontend/package.json
I think this is good, but @HootDunk should `google-libphonenumber` be a non-dev dependency?

2024-02-02 20:29 UTC, HootDunk requested changes
I went ahead and fixed these up in my PR so you can close this one

2024-02-02 21:16 UTC, closed without merging